services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT:-3306}:3306

  wp:
    image: wordpress:${WORDPRESS_VERSION}
    user: ${PUID}:${PGID}
    restart: on-failure
    volumes:
      - ./public_html:/var/www/html
      - ./docker/wordpress/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      WORDPRESS_CONFIG_EXTRA: |
        /* Add any custom values between this line and the "stop editing" line. */
    depends_on:
      - mysql
    ports:
      - ${WORDPRESS_PORT}:80    

  mailhog:
    image: mailhog/mailhog:${MAILHOG_VERSION}
    ports:
      - "${MAILHOG_PORT}:8025"

volumes:
  db_data: